name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'  # lowest julia declared compat in `Project.toml`
          - '1'
        experimental:
          - false
        os: [ubuntu-latest]
        arch: [x64]
        include:  # spare windows/macos CI credits
          - os: windows-latest
            experimental: false
            version: '1'
            arch: x64
          - os: macOS-latest
            experimental: false
            version: '1'
            arch: x64
          - os: ubuntu-latest
            experimental: true
            version: '~1.11.0-0'
            arch: x64
          - os: ubuntu-latest
            experimental: true
            version: 'nightly'
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - name: install latex dependencies
        if: startsWith(matrix.os,'ubuntu')
        run: |
          sudo apt-get -y update
          sudo apt-get -y install latexmk texlive-{luatex,latex-extra}
          sudo fc-cache -vr
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      # - run: |
      #     julia --project=docs -e '
      #       using Documenter: doctest
      #       using Latexify
      #       doctest(Latexify)' 
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
